### PR TITLE
Add a placeholder option to the column filter options

### PR DESCRIPTION
**Pull request by heymagurany**
screen shot 2016-11-14 at 5 46 45 pm

The placeholder option that you specify will set the `placeholder` attribute of the input helper for the 'search' type and will be used for the label of the default option for the 'select' type.

### CODE REVIEW

**Comment by smargovsky** [comment]
@heymagurany Quick question, what happens if one doesn't specify a placeholder for a filter?  I think Handlebars is smart enough to render nothing, but I guess I'm too lazy to build this to find out...:)

**Comment by menewman** [comment]
@heymagurany This PR (addressing issue #72) seems fine to me. One thing, though -- would you mind adding a description of this functionality to the Filtering section of the README? It's always nice to document new features as they're added. :)

**Comment by heymagurany** [comment]
@smargovsky I should probably add a test for that. It just doesn't render the placeholder.

@menewman Will do.

**Comment by heymagurany** [comment]
@smargovsky @menewman Should I bump the package minor version?

**Comment by menewman** [comment]
@heymagurany - No, let's not bump the version in this PR. Keeping addon dependencies consistent across Ember engines has (unfortunately) been a pain point so far, so I think we should do whatever we can to be conscientious about releasing new versions (even minor ones). Consequently, I'm in favor of separating PRs from version bumps and trying to bundle several PRs into a single version/release whenever practical.

**Pull request merged**
